format = "$directory$git_branch$git_status$cmd_duration$character"

[directory]
truncation_length = 3
truncate_to_repo  = true
style             = "bold cyan"
read_only         = " 󰌾"

[git_branch]
symbol = " "
style  = "bold yellow"
format = "[$symbol$branch]($style) "

[git_status]
style    = "bold red"
format   = '([$all_status$ahead_behind]($style) )'
modified = "!${count} "
staged   = "+${count} "
untracked = "?${count} "
ahead    = "⇡${count} "
behind   = "⇣${count} "
diverged = "⇕ "

[cmd_duration]
min_time = 2_000
format   = "[${duration}](dimmed yellow) "

[character]
success_symbol = "[❯](bold green)"
error_symbol   = "[❯](bold red)"

[python]
disabled = true

[nodejs]
disabled = true

[rust]
disabled = true

[golang]
disabled = true
